### ISSUE TITLE
US English option outputs British English

### ISSUE THREAD

**Issue by Muon** [dyslexic-charactersheets/website#2]
Hi! Just wanted to report a small bug with the language options. When choosing the US English language option on the character sheets, the output is still with the default (British) English spellings. The other language options seem to work normally, though.

**Comment by marcus-downing** [comment]
Yeah, the US English translation isn't very thorough - there are lots of words that should be translated but just aren't. I'm not the right person to address this, because - of course - when I look at the sheet, all the spellings look correct to me.

Do you want to try and help?

**Comment by Muon** [comment]
I could certainly give it a shot! Can't promise I'll finish all of it, though. Hopefully, it'll mostly just be running a US spell-checker on the text.

**Comment by marcus-downing** [comment]
There's no private messaging on GitHub, so drop me a note using the form on the website -- with your email address -- and I'll set you up an account.
